[build]
  publish = "build"
  functions = './functions/'

[[headers]]
  # Define which paths this specific [[headers]] block will cover.
  for = "/functions/**/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"